# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/costume.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.Costume" do
    value :COSTUME_UNSET, 0
    value :HOLIDAY_2016, 1
    value :ANNIVERSARY, 2
  end
end

module POGOProtos
  module Enums
    Costume = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.Costume").enummodule
  end
end
