# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/encounter_type.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.EncounterType" do
    value :SPAWN_POINT, 0
    value :INCENSE, 1
    value :DISK, 2
  end
end

module POGOProtos
  module Enums
    EncounterType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.EncounterType").enummodule
  end
end
