# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/filter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.Filter" do
    value :UNSET_FILTER, 0
    value :ALL, 1
    value :DEFAULT, 2
    value :OWNED, 3
    value :FEATURED, 4
    value :PURCHASABLE, 5
    value :UNLOCKABLE, 6
  end
end

module POGOProtos
  module Enums
    Filter = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.Filter").enummodule
  end
end
