# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/form.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.Form" do
    value :FORM_UNSET, 0
    value :UNOWN_A, 1
    value :UNOWN_B, 2
    value :UNOWN_C, 3
    value :UNOWN_D, 4
    value :UNOWN_E, 5
    value :UNOWN_F, 6
    value :UNOWN_G, 7
    value :UNOWN_H, 8
    value :UNOWN_I, 9
    value :UNOWN_J, 10
    value :UNOWN_K, 11
    value :UNOWN_L, 12
    value :UNOWN_M, 13
    value :UNOWN_N, 14
    value :UNOWN_O, 15
    value :UNOWN_P, 16
    value :UNOWN_Q, 17
    value :UNOWN_R, 18
    value :UNOWN_S, 19
    value :UNOWN_T, 20
    value :UNOWN_U, 21
    value :UNOWN_V, 22
    value :UNOWN_W, 23
    value :UNOWN_X, 24
    value :UNOWN_Y, 25
    value :UNOWN_Z, 26
    value :UNOWN_EXCLAMATION_POINT, 27
    value :UNOWN_QUESTION_MARK, 28
  end
end

module POGOProtos
  module Enums
    Form = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.Form").enummodule
  end
end
