# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/gender.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.Gender" do
    value :GENDER_UNSET, 0
    value :MALE, 1
    value :FEMALE, 2
    value :GENDERLESS, 3
  end
end

module POGOProtos
  module Enums
    Gender = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.Gender").enummodule
  end
end
