# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/iap_item_category.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.HoloIapItemCategory" do
    value :IAP_CATEGORY_NONE, 0
    value :IAP_CATEGORY_BUNDLE, 1
    value :IAP_CATEGORY_ITEMS, 2
    value :IAP_CATEGORY_UPGRADES, 3
    value :IAP_CATEGORY_POKECOINS, 4
    value :IAP_CATEGORY_AVATAR, 5
  end
end

module POGOProtos
  module Enums
    HoloIapItemCategory = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.HoloIapItemCategory").enummodule
  end
end
