# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/pokemon_rarity.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.PokemonRarity" do
    value :POKEMON_RARITY_NORMAL, 0
    value :POKEMON_RARITY_LEGENDARY, 1
    value :POKEMON_RARITY_MYTHIC, 2
  end
end

module POGOProtos
  module Enums
    PokemonRarity = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.PokemonRarity").enummodule
  end
end
