# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/quest_type.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.QuestType" do
    value :QUEST_UNKNOWN_TYPE, 0
    value :QUEST_FIRST_CATCH_OF_THE_DAY, 1
    value :QUEST_FIRST_POKESTOP_OF_THE_DAY, 2
  end
end

module POGOProtos
  module Enums
    QuestType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.QuestType").enummodule
  end
end
