# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/slot.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.Slot" do
    value :UNSET_SLOT, 0
    value :HAIR, 1
    value :SHIRT, 2
    value :PANTS, 3
    value :HAT, 4
    value :SHOES, 5
    value :EYES, 6
    value :BACKPACK, 7
    value :GLOVES, 8
    value :SOCKS, 9
    value :BELT, 10
    value :GLASSES, 11
    value :NECKLACE, 12
  end
end

module POGOProtos
  module Enums
    Slot = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.Slot").enummodule
  end
end
