# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/map/pokemon/nearby_pokemon.proto

require 'google/protobuf'

require 'pogoprotos/enums/pokemon_id_pb'
require 'pogoprotos/data/pokemon_display_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Map.Pokemon.NearbyPokemon" do
    optional :pokemon_id, :enum, 1, "POGOProtos.Enums.PokemonId"
    optional :distance_in_meters, :float, 2
    optional :encounter_id, :fixed64, 3
    optional :fort_id, :string, 4
    optional :fort_image_url, :string, 5
    optional :pokemon_display, :message, 6, "POGOProtos.Data.PokemonDisplay"
  end
end

module POGOProtos
  module Map
    module Pokemon
      NearbyPokemon = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.Pokemon.NearbyPokemon").msgclass
    end
  end
end
