# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/responses/buy_item_android_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse.Status"
    optional :purchase_token, :string, 2
  end
  add_enum "POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse.Status" do
    value :UNKNOWN, 0
    value :SUCCESS, 1
  end
end

module POGOProtos
  module Networking
    module Platform
      module Responses
        BuyItemAndroidResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse").msgclass
        BuyItemAndroidResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse.Status").enummodule
      end
    end
  end
end
