# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/responses/buy_item_poke_coins_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.Status"
  end
  add_enum "POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.Status" do
    value :UNKNOWN, 0
    value :SUCCESS, 1
    value :NOT_ENOUGH_POKECOINS, 3
  end
end

module POGOProtos
  module Networking
    module Platform
      module Responses
        BuyItemPokeCoinsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse").msgclass
        BuyItemPokeCoinsResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.Status").enummodule
      end
    end
  end
end
