# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/responses/get_store_items_response.proto

require 'google/protobuf'

require 'pogoprotos/data/player/currency_pb'
require 'pogoprotos/inventory/item/item_data_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse" do
    optional :status, :enum, 1, "POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.Status"
    repeated :items, :message, 2, "POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem"
    repeated :player_currencies, :message, 3, "POGOProtos.Data.Player.Currency"
    optional :unknown4, :string, 4
  end
  add_message "POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem" do
    optional :item_id, :string, 1
    optional :is_iap, :bool, 2
    optional :currency_to_buy, :message, 3, "POGOProtos.Data.Player.Currency"
    optional :yields_currency, :message, 4, "POGOProtos.Data.Player.Currency"
    optional :yields_item, :message, 5, "POGOProtos.Inventory.Item.ItemData"
    map :tags, :string, :string, 6
    optional :unknown7, :int32, 7
  end
  add_enum "POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.Status" do
    value :UNDEFINED, 0
    value :OKAY, 1
  end
end

module POGOProtos
  module Networking
    module Platform
      module Responses
        GetStoreItemsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse").msgclass
        GetStoreItemsResponse::StoreItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem").msgclass
        GetStoreItemsResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.Status").enummodule
      end
    end
  end
end
