# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/responses/send_encrypted_signature_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Platform.Responses.SendEncryptedSignatureResponse" do
    optional :received, :bool, 1
  end
end

module POGOProtos
  module Networking
    module Platform
      module Responses
        SendEncryptedSignatureResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Responses.SendEncryptedSignatureResponse").msgclass
      end
    end
  end
end
