# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/responses/unknown_ptr8_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Platform.Responses.UnknownPtr8Response" do
    optional :message, :string, 2
  end
end

module POGOProtos
  module Networking
    module Platform
      module Responses
        UnknownPtr8Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Responses.UnknownPtr8Response").msgclass
      end
    end
  end
end
