# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/item/battle_attributes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Item.BattleAttributes" do
    optional :sta_percent, :float, 1
  end
end

module POGOProtos
  module Settings
    module Master
      module Item
        BattleAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Item.BattleAttributes").msgclass
      end
    end
  end
end
