# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/item/food_attributes.proto

require 'google/protobuf'

require 'pogoprotos/enums/item_effect_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Item.FoodAttributes" do
    repeated :item_effect, :enum, 1, "POGOProtos.Enums.ItemEffect"
    repeated :item_effect_percent, :float, 2
    optional :growth_percent, :float, 3
  end
end

module POGOProtos
  module Settings
    module Master
      module Item
        FoodAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Item.FoodAttributes").msgclass
      end
    end
  end
end
