# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/item/inventory_upgrade_attributes.proto

require 'google/protobuf'

require 'pogoprotos/inventory/inventory_upgrade_type_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Item.InventoryUpgradeAttributes" do
    optional :additional_storage, :int32, 1
    optional :upgrade_type, :enum, 2, "POGOProtos.Inventory.InventoryUpgradeType"
  end
end

module POGOProtos
  module Settings
    module Master
      module Item
        InventoryUpgradeAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Item.InventoryUpgradeAttributes").msgclass
      end
    end
  end
end
