# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/requests/buy_item_android_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Platform.Requests.BuyItemAndroidRequest" do
    optional :buy_item_intent, :string, 1
  end
end

module POGOProtos
  module Networking
    module Platform
      module Requests
        BuyItemAndroidRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Requests.BuyItemAndroidRequest").msgclass
      end
    end
  end
end
