# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/requests/buy_item_poke_coins_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Platform.Requests.BuyItemPokeCoinsRequest" do
    optional :item_id, :string, 1
  end
end

module POGOProtos
  module Networking
    module Platform
      module Requests
        BuyItemPokeCoinsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Requests.BuyItemPokeCoinsRequest").msgclass
      end
    end
  end
end
