# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/requests/send_encrypted_signature_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest" do
    optional :encrypted_signature, :bytes, 1
  end
end

module POGOProtos
  module Networking
    module Platform
      module Requests
        SendEncryptedSignatureRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest").msgclass
      end
    end
  end
end
