# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/requests/unknown_ptr8_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Platform.Requests.UnknownPtr8Request" do
    optional :message, :string, 1
  end
end

module POGOProtos
  module Networking
    module Platform
      module Requests
        UnknownPtr8Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.Requests.UnknownPtr8Request").msgclass
      end
    end
  end
end
