# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/logs/action_log_entry.proto

require 'google/protobuf'

require 'pogoprotos/data/logs/catch_pokemon_log_entry_pb'
require 'pogoprotos/data/logs/fort_search_log_entry_pb'
require 'pogoprotos/data/logs/buddy_pokemon_log_entry_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Logs.ActionLogEntry" do
    optional :timestamp_ms, :int64, 1
    optional :sfida, :bool, 2
    oneof :Action do
      optional :catch_pokemon, :message, 3, "POGOProtos.Data.Logs.CatchPokemonLogEntry"
      optional :fort_search, :message, 4, "POGOProtos.Data.Logs.FortSearchLogEntry"
      optional :buddy_pokemon, :message, 5, "POGOProtos.Data.Logs.BuddyPokemonLogEntry"
    end
  end
end

module POGOProtos
  module Data
    module Logs
      ActionLogEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Logs.ActionLogEntry").msgclass
    end
  end
end
