# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/logs/catch_pokemon_log_entry.proto

require 'google/protobuf'

require 'pogoprotos/enums/pokemon_id_pb'
require 'pogoprotos/data/pokemon_display_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Logs.CatchPokemonLogEntry" do
    optional :result, :enum, 1, "POGOProtos.Data.Logs.CatchPokemonLogEntry.Result"
    optional :pokemon_id, :enum, 2, "POGOProtos.Enums.PokemonId"
    optional :combat_points, :int32, 3
    optional :pokemon_data_id, :fixed64, 4
    optional :pokemon_display, :message, 5, "POGOProtos.Data.PokemonDisplay"
  end
  add_enum "POGOProtos.Data.Logs.CatchPokemonLogEntry.Result" do
    value :UNSET, 0
    value :POKEMON_CAPTURED, 1
    value :POKEMON_FLED, 2
    value :POKEMON_HATCHED, 3
  end
end

module POGOProtos
  module Data
    module Logs
      CatchPokemonLogEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Logs.CatchPokemonLogEntry").msgclass
      CatchPokemonLogEntry::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Logs.CatchPokemonLogEntry.Result").enummodule
    end
  end
end
