# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/envelopes/request_envelope.proto

require 'google/protobuf'

require 'pogoprotos/networking/requests/request_pb'
require 'pogoprotos/networking/envelopes/auth_ticket_pb'
require 'pogoprotos/networking/platform/platform_request_type_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Envelopes.RequestEnvelope" do
    optional :status_code, :int32, 1
    optional :request_id, :uint64, 3
    repeated :requests, :message, 4, "POGOProtos.Networking.Requests.Request"
    repeated :platform_requests, :message, 6, "POGOProtos.Networking.Envelopes.RequestEnvelope.PlatformRequest"
    optional :latitude, :double, 7
    optional :longitude, :double, 8
    optional :accuracy, :double, 9
    optional :auth_info, :message, 10, "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo"
    optional :auth_ticket, :message, 11, "POGOProtos.Networking.Envelopes.AuthTicket"
    optional :ms_since_last_locationfix, :int64, 12
  end
  add_message "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo" do
    optional :provider, :string, 1
    optional :token, :message, 2, "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo.JWT"
  end
  add_message "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo.JWT" do
    optional :contents, :string, 1
    optional :unknown2, :int32, 2
  end
  add_message "POGOProtos.Networking.Envelopes.RequestEnvelope.PlatformRequest" do
    optional :type, :enum, 1, "POGOProtos.Networking.Platform.PlatformRequestType"
    optional :request_message, :bytes, 2
  end
end

module POGOProtos
  module Networking
    module Envelopes
      RequestEnvelope = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.RequestEnvelope").msgclass
      RequestEnvelope::AuthInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo").msgclass
      RequestEnvelope::AuthInfo::JWT = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo.JWT").msgclass
      RequestEnvelope::PlatformRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.RequestEnvelope.PlatformRequest").msgclass
    end
  end
end
