# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/envelopes/response_envelope.proto

require 'google/protobuf'

require 'pogoprotos/networking/envelopes/auth_ticket_pb'
require 'pogoprotos/networking/platform/platform_request_type_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Envelopes.ResponseEnvelope" do
    optional :status_code, :enum, 1, "POGOProtos.Networking.Envelopes.ResponseEnvelope.StatusCode"
    optional :request_id, :uint64, 2
    optional :api_url, :string, 3
    repeated :platform_returns, :message, 6, "POGOProtos.Networking.Envelopes.ResponseEnvelope.PlatformResponse"
    optional :auth_ticket, :message, 7, "POGOProtos.Networking.Envelopes.AuthTicket"
    repeated :returns, :bytes, 100
    optional :error, :string, 101
  end
  add_message "POGOProtos.Networking.Envelopes.ResponseEnvelope.PlatformResponse" do
    optional :type, :enum, 1, "POGOProtos.Networking.Platform.PlatformRequestType"
    optional :response, :bytes, 2
  end
  add_enum "POGOProtos.Networking.Envelopes.ResponseEnvelope.StatusCode" do
    value :UNKNOWN, 0
    value :OK, 1
    value :OK_RPC_URL_IN_RESPONSE, 2
    value :BAD_REQUEST, 3
    value :INVALID_REQUEST, 51
    value :INVALID_PLATFORM_REQUEST, 52
    value :REDIRECT, 53
    value :SESSION_INVALIDATED, 100
    value :INVALID_AUTH_TOKEN, 102
  end
end

module POGOProtos
  module Networking
    module Envelopes
      ResponseEnvelope = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.ResponseEnvelope").msgclass
      ResponseEnvelope::PlatformResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.ResponseEnvelope.PlatformResponse").msgclass
      ResponseEnvelope::StatusCode = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.ResponseEnvelope.StatusCode").enummodule
    end
  end
end
