# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/envelopes/signature.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Envelopes.Signature" do
    repeated :field1, :message, 1, "POGOProtos.Networking.Envelopes.UnknownMessage"
    optional :timestamp_since_start, :uint64, 2
    optional :field3, :string, 3
    repeated :location_fix, :message, 4, "POGOProtos.Networking.Envelopes.Signature.LocationFix"
    repeated :gps_info, :message, 5, "POGOProtos.Networking.Envelopes.Signature.AndroidGpsInfo"
    repeated :field6, :message, 6, "POGOProtos.Networking.Envelopes.UnknownMessage"
    repeated :sensor_info, :message, 7, "POGOProtos.Networking.Envelopes.Signature.SensorInfo"
    optional :device_info, :message, 8, "POGOProtos.Networking.Envelopes.Signature.DeviceInfo"
    optional :activity_status, :message, 9, "POGOProtos.Networking.Envelopes.Signature.ActivityStatus"
    optional :location_hash1, :int32, 10
    optional :field11, :bool, 11
    optional :field12, :bool, 12
    optional :field13, :int32, 13
    optional :field14, :int32, 14
    optional :field15, :string, 15
    optional :field16, :int32, 16
    optional :field17, :string, 17
    optional :field18, :string, 18
    optional :field19, :bool, 19
    optional :location_hash2, :int32, 20
    optional :field21, :bool, 21
    optional :session_hash, :bytes, 22
    optional :timestamp, :uint64, 23
    repeated :request_hash, :uint64, 24
    optional :unknown25, :int64, 25
  end
  add_message "POGOProtos.Networking.Envelopes.Signature.LocationFix" do
    optional :provider, :string, 1
    optional :timestamp_snapshot, :uint64, 2
    optional :altitude, :float, 4
    optional :latitude, :float, 13
    optional :longitude, :float, 14
    optional :speed, :float, 18
    optional :course, :float, 20
    optional :horizontal_accuracy, :float, 21
    optional :vertical_accuracy, :float, 22
    optional :provider_status, :uint64, 26
    optional :floor, :uint32, 27
    optional :location_type, :uint64, 28
  end
  add_message "POGOProtos.Networking.Envelopes.Signature.AndroidGpsInfo" do
    optional :time_to_fix, :uint64, 1
    repeated :satellites_prn, :int32, 2
    repeated :azimuth, :float, 3
    repeated :elevation, :float, 4
    repeated :snr, :float, 5
    repeated :has_almanac, :bool, 6
    repeated :has_ephemeris, :bool, 7
    repeated :used_in_fix, :bool, 8
  end
  add_message "POGOProtos.Networking.Envelopes.Signature.SensorInfo" do
    optional :timestamp_snapshot, :uint64, 1
    optional :linear_acceleration_x, :double, 3
    optional :linear_acceleration_y, :double, 4
    optional :linear_acceleration_z, :double, 5
    optional :magnetic_field_x, :double, 6
    optional :magnetic_field_y, :double, 7
    optional :magnetic_field_z, :double, 8
    optional :magnetic_field_accuracy, :int32, 9
    optional :attitude_pitch, :double, 10
    optional :attitude_yaw, :double, 11
    optional :attitude_roll, :double, 12
    optional :rotation_rate_x, :double, 13
    optional :rotation_rate_y, :double, 14
    optional :rotation_rate_z, :double, 15
    optional :gravity_x, :double, 16
    optional :gravity_y, :double, 17
    optional :gravity_z, :double, 18
    optional :status, :int32, 19
  end
  add_message "POGOProtos.Networking.Envelopes.Signature.DeviceInfo" do
    optional :device_id, :string, 1
    optional :android_board_name, :string, 2
    optional :android_bootloader, :string, 3
    optional :device_brand, :string, 4
    optional :device_model, :string, 5
    optional :device_model_identifier, :string, 6
    optional :device_model_boot, :string, 7
    optional :hardware_manufacturer, :string, 8
    optional :hardware_model, :string, 9
    optional :firmware_brand, :string, 10
    optional :firmware_tags, :string, 12
    optional :firmware_type, :string, 13
    optional :firmware_fingerprint, :string, 14
  end
  add_message "POGOProtos.Networking.Envelopes.Signature.ActivityStatus" do
    optional :start_time_ms, :uint64, 1
    optional :unknown_status, :bool, 2
    optional :walking, :bool, 3
    optional :running, :bool, 4
    optional :stationary, :bool, 5
    optional :automotive, :bool, 6
    optional :tilting, :bool, 7
    optional :cycling, :bool, 8
    optional :status, :bytes, 9
  end
  add_message "POGOProtos.Networking.Envelopes.UnknownMessage" do
  end
end

module POGOProtos
  module Networking
    module Envelopes
      Signature = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature").msgclass
      Signature::LocationFix = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature.LocationFix").msgclass
      Signature::AndroidGpsInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature.AndroidGpsInfo").msgclass
      Signature::SensorInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature.SensorInfo").msgclass
      Signature::DeviceInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature.DeviceInfo").msgclass
      Signature::ActivityStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature.ActivityStatus").msgclass
      UnknownMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.UnknownMessage").msgclass
    end
  end
end
