# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/avatar/avatar_item.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Avatar.AvatarItem" do
    optional :avatar_template_id, :string, 1
    optional :new_timestamp_ms, :int64, 2
    optional :viewed, :bool, 3
  end
end

module POGOProtos
  module Data
    module Avatar
      AvatarItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Avatar.AvatarItem").msgclass
    end
  end
end
