# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/avatar/avatar_customization.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Avatar.AvatarCustomization" do
    optional :avatar_template_id, :string, 1
    repeated :labels, :enum, 2, "POGOProtos.Data.Avatar.AvatarCustomization.Label"
  end
  add_enum "POGOProtos.Data.Avatar.AvatarCustomization.Label" do
    value :UNSET_LABEL, 0
    value :DEFAULT, 1
    value :OWNED, 2
    value :FEATURED, 3
    value :NEW, 4
    value :SALE, 5
    value :PURCHASABLE, 6
    value :UNLOCKABLE, 7
    value :VIEWED, 8
    value :LOCKED_PURCHASABLE, 9
  end
end

module POGOProtos
  module Data
    module Avatar
      AvatarCustomization = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Avatar.AvatarCustomization").msgclass
      AvatarCustomization::Label = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Avatar.AvatarCustomization.Label").enummodule
    end
  end
end
