# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/inventory/applied_items.proto

require 'google/protobuf'

require 'pogoprotos/inventory/applied_item_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.AppliedItems" do
    repeated :item, :message, 4, "POGOProtos.Inventory.AppliedItem"
  end
end

module POGOProtos
  module Inventory
    AppliedItems = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.AppliedItems").msgclass
  end
end
