# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/inventory/candy.proto

require 'google/protobuf'

require 'pogoprotos/enums/pokemon_family_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.Candy" do
    optional :family_id, :enum, 1, "POGOProtos.Enums.PokemonFamilyId"
    optional :candy, :int32, 2
  end
end

module POGOProtos
  module Inventory
    Candy = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.Candy").msgclass
  end
end
