# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/inventory/inventory_item_data.proto

require 'google/protobuf'

require 'pogoprotos/inventory/item/item_data_pb'
require 'pogoprotos/inventory/applied_items_pb'
require 'pogoprotos/inventory/egg_incubators_pb'
require 'pogoprotos/inventory/candy_pb'
require 'pogoprotos/inventory/inventory_upgrades_pb'
require 'pogoprotos/data/avatar/avatar_item_pb'
require 'pogoprotos/data/pokemon_data_pb'
require 'pogoprotos/data/pokedex_entry_pb'
require 'pogoprotos/data/player/player_stats_pb'
require 'pogoprotos/data/player/player_currency_pb'
require 'pogoprotos/data/player/player_camera_pb'
require 'pogoprotos/data/quests/quest_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.InventoryItemData" do
    optional :pokemon_data, :message, 1, "POGOProtos.Data.PokemonData"
    optional :item, :message, 2, "POGOProtos.Inventory.Item.ItemData"
    optional :pokedex_entry, :message, 3, "POGOProtos.Data.PokedexEntry"
    optional :player_stats, :message, 4, "POGOProtos.Data.Player.PlayerStats"
    optional :player_currency, :message, 5, "POGOProtos.Data.Player.PlayerCurrency"
    optional :player_camera, :message, 6, "POGOProtos.Data.Player.PlayerCamera"
    optional :inventory_upgrades, :message, 7, "POGOProtos.Inventory.InventoryUpgrades"
    optional :applied_items, :message, 8, "POGOProtos.Inventory.AppliedItems"
    optional :egg_incubators, :message, 9, "POGOProtos.Inventory.EggIncubators"
    optional :candy, :message, 10, "POGOProtos.Inventory.Candy"
    optional :quest, :message, 11, "POGOProtos.Data.Quests.Quest"
    optional :avatar_item, :message, 12, "POGOProtos.Data.Avatar.AvatarItem"
  end
end

module POGOProtos
  module Inventory
    InventoryItemData = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.InventoryItemData").msgclass
  end
end
