# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/inventory/inventory_upgrades.proto

require 'google/protobuf'

require 'pogoprotos/inventory/inventory_upgrade_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.InventoryUpgrades" do
    repeated :inventory_upgrades, :message, 1, "POGOProtos.Inventory.InventoryUpgrade"
  end
end

module POGOProtos
  module Inventory
    InventoryUpgrades = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.InventoryUpgrades").msgclass
  end
end
