# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/inventory/inventory_upgrade.proto

require 'google/protobuf'

require 'pogoprotos/inventory/item/item_id_pb'
require 'pogoprotos/inventory/inventory_upgrade_type_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.InventoryUpgrade" do
    optional :item_id, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :upgrade_type, :enum, 2, "POGOProtos.Inventory.InventoryUpgradeType"
    optional :additional_storage, :int32, 3
  end
end

module POGOProtos
  module Inventory
    InventoryUpgrade = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.InventoryUpgrade").msgclass
  end
end
