# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/inventory/inventory_item.proto

require 'google/protobuf'

require 'pogoprotos/inventory/inventory_item_data_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.InventoryItem" do
    optional :modified_timestamp_ms, :int64, 1
    optional :deleted_item, :message, 2, "POGOProtos.Inventory.InventoryItem.DeletedItem"
    optional :inventory_item_data, :message, 3, "POGOProtos.Inventory.InventoryItemData"
  end
  add_message "POGOProtos.Inventory.InventoryItem.DeletedItem" do
    optional :pokemon_id, :fixed64, 1
  end
end

module POGOProtos
  module Inventory
    InventoryItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.InventoryItem").msgclass
    InventoryItem::DeletedItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.InventoryItem.DeletedItem").msgclass
  end
end
