# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/inventory/inventory_key.proto

require 'google/protobuf'

require 'pogoprotos/enums/quest_type_pb'
require 'pogoprotos/enums/pokemon_family_id_pb'
require 'pogoprotos/inventory/item/item_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.InventoryKey" do
    optional :pokemon_id, :fixed64, 1
    optional :item, :enum, 2, "POGOProtos.Inventory.Item.ItemId"
    optional :pokedex_entry_id, :int32, 3
    optional :player_stats, :bool, 4
    optional :player_currency, :bool, 5
    optional :player_camera, :bool, 6
    optional :inventory_upgrades, :bool, 7
    optional :applied_items, :bool, 8
    optional :egg_incubators, :bool, 9
    optional :pokemon_family_id, :enum, 10, "POGOProtos.Enums.PokemonFamilyId"
    optional :quest_type, :enum, 11, "POGOProtos.Enums.QuestType"
    optional :avatar_template_id, :string, 12
  end
end

module POGOProtos
  module Inventory
    InventoryKey = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.InventoryKey").msgclass
  end
end
