# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/event_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.EventSettings" do
    repeated :condolence_ribbon_country, :string, 1
  end
end

module POGOProtos
  module Settings
    EventSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.EventSettings").msgclass
  end
end
