# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/festival_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.FestivalSettings" do
    optional :festival_type, :enum, 1, "POGOProtos.Settings.FestivalSettings.FestivalType"
    optional :key, :string, 2
    optional :vector, :string, 3
  end
  add_enum "POGOProtos.Settings.FestivalSettings.FestivalType" do
    value :NONE, 0
    value :HALLOWEEN, 1
    value :HOLIDAY, 2
  end
end

module POGOProtos
  module Settings
    FestivalSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.FestivalSettings").msgclass
    FestivalSettings::FestivalType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.FestivalSettings.FestivalType").enummodule
  end
end
