# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/global_settings.proto

require 'google/protobuf'

require 'pogoprotos/settings/event_settings_pb'
require 'pogoprotos/settings/festival_settings_pb'
require 'pogoprotos/settings/fort_settings_pb'
require 'pogoprotos/settings/gps_settings_pb'
require 'pogoprotos/settings/inventory_settings_pb'
require 'pogoprotos/settings/level_settings_pb'
require 'pogoprotos/settings/map_settings_pb'
require 'pogoprotos/settings/news_settings_pb'
require 'pogoprotos/settings/notification_settings_pb'
require 'pogoprotos/settings/passcode_settings_pb'
require 'pogoprotos/settings/sfida_settings_pb'
require 'pogoprotos/settings/translation_settings_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.GlobalSettings" do
    optional :fort_settings, :message, 2, "POGOProtos.Settings.FortSettings"
    optional :map_settings, :message, 3, "POGOProtos.Settings.MapSettings"
    optional :level_settings, :message, 4, "POGOProtos.Settings.LevelSettings"
    optional :inventory_settings, :message, 5, "POGOProtos.Settings.InventorySettings"
    optional :minimum_client_version, :string, 6
    optional :gps_settings, :message, 7, "POGOProtos.Settings.GpsSettings"
    optional :festival_settings, :message, 8, "POGOProtos.Settings.FestivalSettings"
    optional :event_settings, :message, 9, "POGOProtos.Settings.EventSettings"
    optional :max_pokemon_types, :int32, 10
    optional :sfida_settings, :message, 11, "POGOProtos.Settings.SfidaSettings"
    optional :news_settings, :message, 12, "POGOProtos.Settings.NewsSettings"
    optional :translation_settings, :message, 13, "POGOProtos.Settings.TranslationSettings"
    optional :passcode_settings, :message, 14, "POGOProtos.Settings.PasscodeSettings"
    optional :notification_settings, :message, 15, "POGOProtos.Settings.NotificationSettings"
  end
end

module POGOProtos
  module Settings
    GlobalSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.GlobalSettings").msgclass
  end
end
