# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/gps_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.GpsSettings" do
    optional :driving_warning_speed_meters_per_second, :float, 1
    optional :driving_warning_cooldown_minutes, :float, 2
    optional :driving_speed_sample_interval_seconds, :float, 3
    optional :driving_speed_sample_count, :int32, 4
  end
end

module POGOProtos
  module Settings
    GpsSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.GpsSettings").msgclass
  end
end
