# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/notification_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.NotificationSettings" do
    optional :pull_notifications, :bool, 1
    optional :show_notifications, :bool, 2
  end
end

module POGOProtos
  module Settings
    NotificationSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.NotificationSettings").msgclass
  end
end
