# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/passcode_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.PasscodeSettings" do
    optional :show_passcode_in_store, :bool, 1
  end
end

module POGOProtos
  module Settings
    PasscodeSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.PasscodeSettings").msgclass
  end
end
