# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/sfida_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.SfidaSettings" do
    optional :low_battery_threshold, :float, 1
  end
end

module POGOProtos
  module Settings
    SfidaSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.SfidaSettings").msgclass
  end
end
