# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/translation_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.TranslationSettings" do
    repeated :translation_bundle_ids, :string, 1
  end
end

module POGOProtos
  module Settings
    TranslationSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.TranslationSettings").msgclass
  end
end
