# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/catch_pokemon_message.proto

require 'google/protobuf'

require 'pogoprotos/inventory/item/item_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.CatchPokemonMessage" do
    optional :encounter_id, :fixed64, 1
    optional :pokeball, :enum, 2, "POGOProtos.Inventory.Item.ItemId"
    optional :normalized_reticle_size, :double, 3
    optional :spawn_point_id, :string, 4
    optional :hit_pokemon, :bool, 5
    optional :spin_modifier, :double, 6
    optional :normalized_hit_position, :double, 7
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        CatchPokemonMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.CatchPokemonMessage").msgclass
      end
    end
  end
end
