# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/collect_daily_bonus_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.CollectDailyBonusMessage" do
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        CollectDailyBonusMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.CollectDailyBonusMessage").msgclass
      end
    end
  end
end
