# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/encounter_tutorial_complete_message.proto

require 'google/protobuf'

require 'pogoprotos/enums/pokemon_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.EncounterTutorialCompleteMessage" do
    optional :pokemon_id, :enum, 1, "POGOProtos.Enums.PokemonId"
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        EncounterTutorialCompleteMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.EncounterTutorialCompleteMessage").msgclass
      end
    end
  end
end
