# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/equip_badge_message.proto

require 'google/protobuf'

require 'pogoprotos/enums/badge_type_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.EquipBadgeMessage" do
    optional :badge_type, :enum, 1, "POGOProtos.Enums.BadgeType"
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        EquipBadgeMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.EquipBadgeMessage").msgclass
      end
    end
  end
end
