# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/evolve_pokemon_message.proto

require 'google/protobuf'

require 'pogoprotos/inventory/item/item_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.EvolvePokemonMessage" do
    optional :pokemon_id, :fixed64, 1
    optional :evolution_item_requirement, :enum, 2, "POGOProtos.Inventory.Item.ItemId"
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        EvolvePokemonMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.EvolvePokemonMessage").msgclass
      end
    end
  end
end
