# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/fort_recall_pokemon_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.FortRecallPokemonMessage" do
    optional :fort_id, :string, 1
    optional :pokemon_id, :fixed64, 2
    optional :player_latitude, :double, 3
    optional :player_longitude, :double, 4
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        FortRecallPokemonMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.FortRecallPokemonMessage").msgclass
      end
    end
  end
end
