# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/get_player_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.GetPlayerMessage" do
    optional :player_locale, :message, 1, "POGOProtos.Networking.Requests.Messages.GetPlayerMessage.PlayerLocale"
  end
  add_message "POGOProtos.Networking.Requests.Messages.GetPlayerMessage.PlayerLocale" do
    optional :country, :string, 1
    optional :language, :string, 2
    optional :timezone, :string, 3
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        GetPlayerMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.GetPlayerMessage").msgclass
        GetPlayerMessage::PlayerLocale = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.GetPlayerMessage.PlayerLocale").msgclass
      end
    end
  end
end
