# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/get_inbox_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.GetInboxMessage" do
    optional :is_history, :bool, 1
    optional :is_reverse, :bool, 2
    optional :not_before_ms, :int64, 3
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        GetInboxMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.GetInboxMessage").msgclass
      end
    end
  end
end
