# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/get_buddy_walked_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.GetBuddyWalkedMessage" do
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        GetBuddyWalkedMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.GetBuddyWalkedMessage").msgclass
      end
    end
  end
end
