# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/get_asset_digest_message.proto

require 'google/protobuf'

require 'pogoprotos/enums/platform_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.GetAssetDigestMessage" do
    optional :platform, :enum, 1, "POGOProtos.Enums.Platform"
    optional :device_manufacturer, :string, 2
    optional :device_model, :string, 3
    optional :locale, :string, 4
    optional :app_version, :uint32, 5
    optional :paginate, :bool, 6
    optional :page_offset, :int32, 7
    optional :page_timestamp, :uint64, 8
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        GetAssetDigestMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.GetAssetDigestMessage").msgclass
      end
    end
  end
end
