# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/incense_encounter_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.IncenseEncounterMessage" do
    optional :encounter_id, :uint64, 1
    optional :encounter_location, :string, 2
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        IncenseEncounterMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.IncenseEncounterMessage").msgclass
      end
    end
  end
end
