# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/register_background_device_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.RegisterBackgroundDeviceMessage" do
    optional :device_type, :string, 1
    optional :device_id, :string, 2
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        RegisterBackgroundDeviceMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.RegisterBackgroundDeviceMessage").msgclass
      end
    end
  end
end
