# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/release_pokemon_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.ReleasePokemonMessage" do
    optional :pokemon_id, :fixed64, 1
    repeated :pokemon_ids, :fixed64, 2
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        ReleasePokemonMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.ReleasePokemonMessage").msgclass
      end
    end
  end
end
