# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/set_buddy_pokemon_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.SetBuddyPokemonMessage" do
    optional :pokemon_id, :fixed64, 1
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        SetBuddyPokemonMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.SetBuddyPokemonMessage").msgclass
      end
    end
  end
end
