# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/set_contact_settings_message.proto

require 'google/protobuf'

require 'pogoprotos/data/player/contact_settings_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.SetContactSettingsMessage" do
    optional :contact_settings, :message, 1, "POGOProtos.Data.Player.ContactSettings"
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        SetContactSettingsMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.SetContactSettingsMessage").msgclass
      end
    end
  end
end
