# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/set_avatar_item_as_viewed_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.SetAvatarItemAsViewedMessage" do
    repeated :avatar_template_id, :string, 1
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        SetAvatarItemAsViewedMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.SetAvatarItemAsViewedMessage").msgclass
      end
    end
  end
end
