# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/set_player_team_message.proto

require 'google/protobuf'

require 'pogoprotos/enums/team_color_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.SetPlayerTeamMessage" do
    optional :team, :enum, 1, "POGOProtos.Enums.TeamColor"
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        SetPlayerTeamMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.SetPlayerTeamMessage").msgclass
      end
    end
  end
end
