# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/use_item_gym_message.proto

require 'google/protobuf'

require 'pogoprotos/inventory/item/item_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.UseItemGymMessage" do
    optional :item_id, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :gym_id, :string, 2
    optional :player_latitude, :double, 3
    optional :player_longitude, :double, 4
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        UseItemGymMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.UseItemGymMessage").msgclass
      end
    end
  end
end
