# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/use_incense_message.proto

require 'google/protobuf'

require 'pogoprotos/inventory/item/item_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.UseIncenseMessage" do
    optional :incense_type, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        UseIncenseMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.UseIncenseMessage").msgclass
      end
    end
  end
end
