# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/use_item_encounter_message.proto

require 'google/protobuf'

require 'pogoprotos/inventory/item/item_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.UseItemEncounterMessage" do
    optional :item, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :encounter_id, :fixed64, 2
    optional :spawn_point_guid, :string, 3
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        UseItemEncounterMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.UseItemEncounterMessage").msgclass
      end
    end
  end
end
