# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/verify_challenge_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.VerifyChallengeMessage" do
    optional :token, :string, 1
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        VerifyChallengeMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.VerifyChallengeMessage").msgclass
      end
    end
  end
end
