# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/map/fort/fort_lure_info.proto

require 'google/protobuf'

require 'pogoprotos/enums/pokemon_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Map.Fort.FortLureInfo" do
    optional :fort_id, :string, 1
    optional :encounter_id, :fixed64, 2
    optional :active_pokemon_id, :enum, 3, "POGOProtos.Enums.PokemonId"
    optional :lure_expires_timestamp_ms, :int64, 4
  end
end

module POGOProtos
  module Map
    module Fort
      FortLureInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.Fort.FortLureInfo").msgclass
    end
  end
end
