# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/map/fort/fort_data.proto

require 'google/protobuf'

require 'pogoprotos/data/pokemon_display_pb'
require 'pogoprotos/enums/pokemon_id_pb'
require 'pogoprotos/enums/team_color_pb'
require 'pogoprotos/inventory/item/item_id_pb'
require 'pogoprotos/map/fort/fort_type_pb'
require 'pogoprotos/map/fort/fort_sponsor_pb'
require 'pogoprotos/map/fort/fort_rendering_type_pb'
require 'pogoprotos/map/fort/fort_lure_info_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Map.Fort.FortData" do
    optional :id, :string, 1
    optional :last_modified_timestamp_ms, :int64, 2
    optional :latitude, :double, 3
    optional :longitude, :double, 4
    optional :owned_by_team, :enum, 5, "POGOProtos.Enums.TeamColor"
    optional :guard_pokemon_id, :enum, 6, "POGOProtos.Enums.PokemonId"
    optional :guard_pokemon_cp, :int32, 7
    optional :enabled, :bool, 8
    optional :type, :enum, 9, "POGOProtos.Map.Fort.FortType"
    optional :gym_points, :int64, 10
    optional :is_in_battle, :bool, 11
    repeated :active_fort_modifier, :enum, 12, "POGOProtos.Inventory.Item.ItemId"
    optional :lure_info, :message, 13, "POGOProtos.Map.Fort.FortLureInfo"
    optional :cooldown_complete_timestamp_ms, :int64, 14
    optional :sponsor, :enum, 15, "POGOProtos.Map.Fort.FortSponsor"
    optional :rendering_type, :enum, 16, "POGOProtos.Map.Fort.FortRenderingType"
    optional :deploy_lockout_end_ms, :int64, 17
    optional :guard_pokemon_display, :message, 18, "POGOProtos.Data.PokemonDisplay"
    optional :closed, :bool, 19
  end
end

module POGOProtos
  module Map
    module Fort
      FortData = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.Fort.FortData").msgclass
    end
  end
end
