# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/map/fort/fort_sponsor.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Map.Fort.FortSponsor" do
    value :UNSET_SPONSOR, 0
    value :MCDONALDS, 1
    value :POKEMON_STORE, 2
    value :TOHO, 3
    value :SOFTBANK, 4
    value :GLOBE, 5
    value :SPATULA, 6
    value :THERMOMETER, 7
    value :KNIFE, 8
    value :GRILL, 9
    value :SMOKER, 10
    value :PAN, 11
    value :BBQ, 12
    value :FRYER, 13
    value :STEAMER, 14
    value :HOOD, 15
    value :SLOWCOOKER, 16
    value :MIXER, 17
    value :SCOOPER, 18
    value :MUFFINTIN, 19
    value :SALAMANDER, 20
    value :PLANCHA, 21
    value :NIA_OPS, 22
  end
end

module POGOProtos
  module Map
    module Fort
      FortSponsor = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.Fort.FortSponsor").enummodule
    end
  end
end
