# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/platform_request_type.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Networking.Platform.PlatformRequestType" do
    value :METHOD_UNSET, 0
    value :BUY_ITEM_POKECOINS, 2
    value :BUY_ITEM_ANDROID, 3
    value :BUY_ITEM_IOS, 4
    value :GET_STORE_ITEMS, 5
    value :SEND_ENCRYPTED_SIGNATURE, 6
    value :UNKNOWN_PTR_8, 8
  end
end

module POGOProtos
  module Networking
    module Platform
      PlatformRequestType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Platform.PlatformRequestType").enummodule
    end
  end
end
