require "pogoprotos/networking/platform/responses/get_store_items_response"
require "pogoprotos/networking/platform/responses/unknown_ptr8_response"
require "pogoprotos/networking/platform/responses/send_encrypted_signature_response"
require "pogoprotos/networking/platform/responses/buy_item_poke_coins_response"
require "pogoprotos/networking/platform/responses/buy_item_android_response"
