# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/avatar_customization_settings.proto

require 'google/protobuf'

require 'pogoprotos/data/player/player_avatar_type_pb'
require 'pogoprotos/enums/badge_type_pb'
require 'pogoprotos/enums/slot_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.AvatarCustomizationSettings" do
    optional :enabled, :bool, 1
    optional :avatar_type, :enum, 2, "POGOProtos.Data.Player.PlayerAvatarType"
    repeated :slot, :enum, 3, "POGOProtos.Enums.Slot"
    optional :bundle_name, :string, 4
    optional :asset_name, :string, 5
    optional :group_name, :string, 6
    optional :sort_order, :int32, 7
    optional :unlock_type, :enum, 8, "POGOProtos.Settings.Master.AvatarCustomizationSettings.AvatarCustomizationUnlockType"
    repeated :promo_type, :enum, 9, "POGOProtos.Settings.Master.AvatarCustomizationSettings.AvatarCustomizationPromoType"
    optional :unlock_badge_type, :enum, 10, "POGOProtos.Enums.BadgeType"
    optional :iap_sku, :string, 11
    optional :unlock_badge_level, :int32, 12
    optional :icon_name, :string, 13
    optional :unlock_player_level, :int32, 14
  end
  add_enum "POGOProtos.Settings.Master.AvatarCustomizationSettings.AvatarCustomizationPromoType" do
    value :UNSET_PROMO_TYPE, 0
    value :SALE, 1
    value :FEATURED, 2
  end
  add_enum "POGOProtos.Settings.Master.AvatarCustomizationSettings.AvatarCustomizationUnlockType" do
    value :UNSET_UNLOCK_TYPE, 0
    value :DEFAULT, 1
    value :MEDAL_REWARD, 2
    value :IAP_CLOTHING, 3
    value :LEVEL_REWARD, 4
  end
end

module POGOProtos
  module Settings
    module Master
      AvatarCustomizationSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.AvatarCustomizationSettings").msgclass
      AvatarCustomizationSettings::AvatarCustomizationPromoType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.AvatarCustomizationSettings.AvatarCustomizationPromoType").enummodule
      AvatarCustomizationSettings::AvatarCustomizationUnlockType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.AvatarCustomizationSettings.AvatarCustomizationUnlockType").enummodule
    end
  end
end
