# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/item_settings.proto

require 'google/protobuf'

require 'pogoprotos/enums/item_category_pb'
require 'pogoprotos/inventory/item/item_id_pb'
require 'pogoprotos/inventory/item/item_type_pb'
require 'pogoprotos/settings/master/item/food_attributes_pb'
require 'pogoprotos/settings/master/item/potion_attributes_pb'
require 'pogoprotos/settings/master/item/revive_attributes_pb'
require 'pogoprotos/settings/master/item/battle_attributes_pb'
require 'pogoprotos/settings/master/item/incense_attributes_pb'
require 'pogoprotos/settings/master/item/pokeball_attributes_pb'
require 'pogoprotos/settings/master/item/fort_modifier_attributes_pb'
require 'pogoprotos/settings/master/item/egg_incubator_attributes_pb'
require 'pogoprotos/settings/master/item/experience_boost_attributes_pb'
require 'pogoprotos/settings/master/item/inventory_upgrade_attributes_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.ItemSettings" do
    optional :item_id, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :item_type, :enum, 2, "POGOProtos.Inventory.Item.ItemType"
    optional :category, :enum, 3, "POGOProtos.Enums.ItemCategory"
    optional :drop_freq, :float, 4
    optional :drop_trainer_level, :int32, 5
    optional :pokeball, :message, 6, "POGOProtos.Settings.Master.Item.PokeballAttributes"
    optional :potion, :message, 7, "POGOProtos.Settings.Master.Item.PotionAttributes"
    optional :revive, :message, 8, "POGOProtos.Settings.Master.Item.ReviveAttributes"
    optional :battle, :message, 9, "POGOProtos.Settings.Master.Item.BattleAttributes"
    optional :food, :message, 10, "POGOProtos.Settings.Master.Item.FoodAttributes"
    optional :inventory_upgrade, :message, 11, "POGOProtos.Settings.Master.Item.InventoryUpgradeAttributes"
    optional :xp_boost, :message, 12, "POGOProtos.Settings.Master.Item.ExperienceBoostAttributes"
    optional :incense, :message, 13, "POGOProtos.Settings.Master.Item.IncenseAttributes"
    optional :egg_incubator, :message, 14, "POGOProtos.Settings.Master.Item.EggIncubatorAttributes"
    optional :fort_modifier, :message, 15, "POGOProtos.Settings.Master.Item.FortModifierAttributes"
  end
end

module POGOProtos
  module Settings
    module Master
      ItemSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.ItemSettings").msgclass
    end
  end
end
