# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/pokemon_settings.proto

require 'google/protobuf'

require 'pogoprotos/enums/pokemon_id_pb'
require 'pogoprotos/enums/pokemon_rarity_pb'
require 'pogoprotos/enums/pokemon_type_pb'
require 'pogoprotos/enums/pokemon_move_pb'
require 'pogoprotos/enums/pokemon_family_id_pb'
require 'pogoprotos/settings/master/pokemon/stats_attributes_pb'
require 'pogoprotos/settings/master/pokemon/camera_attributes_pb'
require 'pogoprotos/settings/master/pokemon/encounter_attributes_pb'
require 'pogoprotos/settings/master/pokemon/evolution_branch_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.PokemonSettings" do
    optional :pokemon_id, :enum, 1, "POGOProtos.Enums.PokemonId"
    optional :model_scale, :float, 3
    optional :type, :enum, 4, "POGOProtos.Enums.PokemonType"
    optional :type_2, :enum, 5, "POGOProtos.Enums.PokemonType"
    optional :camera, :message, 6, "POGOProtos.Settings.Master.Pokemon.CameraAttributes"
    optional :encounter, :message, 7, "POGOProtos.Settings.Master.Pokemon.EncounterAttributes"
    optional :stats, :message, 8, "POGOProtos.Settings.Master.Pokemon.StatsAttributes"
    repeated :quick_moves, :enum, 9, "POGOProtos.Enums.PokemonMove"
    repeated :cinematic_moves, :enum, 10, "POGOProtos.Enums.PokemonMove"
    repeated :animation_time, :float, 11
    repeated :evolution_ids, :enum, 12, "POGOProtos.Enums.PokemonId"
    optional :evolution_pips, :int32, 13
    optional :rarity, :enum, 14, "POGOProtos.Enums.PokemonRarity"
    optional :pokedex_height_m, :float, 15
    optional :pokedex_weight_kg, :float, 16
    optional :parent_pokemon_id, :enum, 17, "POGOProtos.Enums.PokemonId"
    optional :height_std_dev, :float, 18
    optional :weight_std_dev, :float, 19
    optional :km_distance_to_hatch, :float, 20
    optional :family_id, :enum, 21, "POGOProtos.Enums.PokemonFamilyId"
    optional :candy_to_evolve, :int32, 22
    optional :km_buddy_distance, :float, 23
    optional :buddy_size, :enum, 24, "POGOProtos.Settings.Master.PokemonSettings.BuddySize"
    optional :model_height, :float, 25
    repeated :evolution_branch, :message, 26, "POGOProtos.Settings.Master.Pokemon.EvolutionBranch"
  end
  add_enum "POGOProtos.Settings.Master.PokemonSettings.BuddySize" do
    value :BUDDY_MEDIUM, 0
    value :BUDDY_SHOULDER, 1
    value :BUDDY_BIG, 2
    value :BUDDY_FLYING, 3
    value :BUDDY_BABY, 4
  end
end

module POGOProtos
  module Settings
    module Master
      PokemonSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.PokemonSettings").msgclass
      PokemonSettings::BuddySize = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.PokemonSettings.BuddySize").enummodule
    end
  end
end
