# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/quests/quest.proto

require 'google/protobuf'

require 'pogoprotos/enums/quest_type_pb'
require 'pogoprotos/data/quests/daily_quest_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Quests.Quest" do
    optional :quest_type, :enum, 1, "POGOProtos.Enums.QuestType"
    optional :daily_quest, :message, 2, "POGOProtos.Data.Quests.DailyQuest"
  end
end

module POGOProtos
  module Data
    module Quests
      Quest = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Quests.Quest").msgclass
    end
  end
end
