# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/quest/daily_quest_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Quest.DailyQuestSettings" do
    optional :buckets_per_day, :int32, 1
    optional :streak_length, :int32, 2
    optional :bonus_multiplier, :float, 3
    optional :streak_bonus_multiplier, :float, 4
  end
end

module POGOProtos
  module Settings
    module Master
      module Quest
        DailyQuestSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Quest.DailyQuestSettings").msgclass
      end
    end
  end
end
