# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/background_token.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.BackgroundToken" do
    optional :token, :bytes, 1
    optional :expiration_time, :int64, 2
    optional :iv, :bytes, 3
  end
end

module POGOProtos
  module Data
    BackgroundToken = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.BackgroundToken").msgclass
  end
end
