# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/buddy_pokemon.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.BuddyPokemon" do
    optional :id, :fixed64, 1
    optional :start_km_walked, :double, 2
    optional :last_km_awarded, :double, 3
  end
end

module POGOProtos
  module Data
    BuddyPokemon = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.BuddyPokemon").msgclass
  end
end
