# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/client_version.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.ClientVersion" do
    optional :min_version, :string, 1
  end
end

module POGOProtos
  module Data
    ClientVersion = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.ClientVersion").msgclass
  end
end
