# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/download_url_entry.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.DownloadUrlEntry" do
    optional :asset_id, :string, 1
    optional :url, :string, 2
    optional :size, :int32, 3
    optional :checksum, :fixed32, 4
  end
end

module POGOProtos
  module Data
    DownloadUrlEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.DownloadUrlEntry").msgclass
  end
end
