# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/player_data.proto

require 'google/protobuf'

require 'pogoprotos/enums/tutorial_state_pb'
require 'pogoprotos/data/player/player_avatar_pb'
require 'pogoprotos/data/player/daily_bonus_pb'
require 'pogoprotos/data/player/equipped_badge_pb'
require 'pogoprotos/data/player/contact_settings_pb'
require 'pogoprotos/data/player/currency_pb'
require 'pogoprotos/data/buddy_pokemon_pb'
require 'pogoprotos/enums/team_color_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.PlayerData" do
    optional :creation_timestamp_ms, :int64, 1
    optional :username, :string, 2
    optional :team, :enum, 5, "POGOProtos.Enums.TeamColor"
    repeated :tutorial_state, :enum, 7, "POGOProtos.Enums.TutorialState"
    optional :avatar, :message, 8, "POGOProtos.Data.Player.PlayerAvatar"
    optional :max_pokemon_storage, :int32, 9
    optional :max_item_storage, :int32, 10
    optional :daily_bonus, :message, 11, "POGOProtos.Data.Player.DailyBonus"
    optional :equipped_badge, :message, 12, "POGOProtos.Data.Player.EquippedBadge"
    optional :contact_settings, :message, 13, "POGOProtos.Data.Player.ContactSettings"
    repeated :currencies, :message, 14, "POGOProtos.Data.Player.Currency"
    optional :remaining_codename_claims, :int32, 15
    optional :buddy_pokemon, :message, 16, "POGOProtos.Data.BuddyPokemon"
    optional :battle_lockout_end_ms, :int64, 17
    optional :secondary_player_avatar, :message, 18, "POGOProtos.Data.Player.PlayerAvatar"
    optional :name_is_blacklisted, :bool, 19
  end
end

module POGOProtos
  module Data
    PlayerData = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.PlayerData").msgclass
  end
end
