# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/pokemon_display.proto

require 'google/protobuf'

require 'pogoprotos/enums/costume_pb'
require 'pogoprotos/enums/form_pb'
require 'pogoprotos/enums/gender_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.PokemonDisplay" do
    optional :costume, :enum, 1, "POGOProtos.Enums.Costume"
    optional :gender, :enum, 2, "POGOProtos.Enums.Gender"
    optional :shiny, :bool, 3
    optional :form, :enum, 4, "POGOProtos.Enums.Form"
  end
end

module POGOProtos
  module Data
    PokemonDisplay = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.PokemonDisplay").msgclass
  end
end
