# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/pokedex_entry.proto

require 'google/protobuf'

require 'pogoprotos/enums/costume_pb'
require 'pogoprotos/enums/form_pb'
require 'pogoprotos/enums/gender_pb'
require 'pogoprotos/enums/pokemon_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.PokedexEntry" do
    optional :pokemon_id, :enum, 1, "POGOProtos.Enums.PokemonId"
    optional :times_encountered, :int32, 2
    optional :times_captured, :int32, 3
    optional :evolution_stone_pieces, :int32, 4
    optional :evolution_stones, :int32, 5
    repeated :captured_costumes, :enum, 6, "POGOProtos.Enums.Costume"
    repeated :captured_forms, :enum, 7, "POGOProtos.Enums.Form"
    repeated :captured_genders, :enum, 8, "POGOProtos.Enums.Gender"
    optional :captured_shiny, :bool, 9
    repeated :encountered_costumes, :enum, 10, "POGOProtos.Enums.Costume"
    repeated :encountered_forms, :enum, 11, "POGOProtos.Enums.Form"
    repeated :encountered_genders, :enum, 12, "POGOProtos.Enums.Gender"
    optional :encountered_shiny, :bool, 13
  end
end

module POGOProtos
  module Data
    PokedexEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.PokedexEntry").msgclass
  end
end
