# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/redeem_passcode_reward.proto

require 'google/protobuf'

require 'pogoprotos/data/pokemon_data_pb'
require 'pogoprotos/data/redeem/poke_candy_pb'
require 'pogoprotos/data/redeem/redeemed_avatar_item_pb'
require 'pogoprotos/data/redeem/redeemed_item_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.RedeemPasscodeReward" do
    repeated :items, :message, 1, "POGOProtos.Data.Redeem.RedeemedItem"
    repeated :avatar_items, :message, 2, "POGOProtos.Data.Redeem.RedeemedAvatarItem"
    repeated :egg_pokemon, :message, 3, "POGOProtos.Data.PokemonData"
    repeated :pokemon, :message, 4, "POGOProtos.Data.PokemonData"
    repeated :poke_candy, :message, 5, "POGOProtos.Data.Redeem.PokeCandy"
    optional :stardust, :int32, 6
    optional :pokecoins, :int32, 7
  end
end

module POGOProtos
  module Data
    RedeemPasscodeReward = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.RedeemPasscodeReward").msgclass
  end
end
