# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/add_fort_modifier_response.proto

require 'google/protobuf'

require 'pogoprotos/networking/responses/fort_details_response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.AddFortModifierResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.AddFortModifierResponse.Result"
    optional :fort_details, :message, 2, "POGOProtos.Networking.Responses.FortDetailsResponse"
  end
  add_enum "POGOProtos.Networking.Responses.AddFortModifierResponse.Result" do
    value :NO_RESULT_SET, 0
    value :SUCCESS, 1
    value :FORT_ALREADY_HAS_MODIFIER, 2
    value :TOO_FAR_AWAY, 3
    value :NO_ITEM_IN_INVENTORY, 4
    value :POI_INACCESSIBLE, 5
  end
end

module POGOProtos
  module Networking
    module Responses
      AddFortModifierResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.AddFortModifierResponse").msgclass
      AddFortModifierResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.AddFortModifierResponse.Result").enummodule
    end
  end
end
