# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/check_awarded_badges_response.proto

require 'google/protobuf'

require 'pogoprotos/enums/badge_type_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.CheckAwardedBadgesResponse" do
    optional :success, :bool, 1
    repeated :awarded_badges, :enum, 2, "POGOProtos.Enums.BadgeType"
    repeated :awarded_badge_levels, :int32, 3
    repeated :avatar_template_ids, :string, 4
  end
end

module POGOProtos
  module Networking
    module Responses
      CheckAwardedBadgesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.CheckAwardedBadgesResponse").msgclass
    end
  end
end
