# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/check_challenge_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.CheckChallengeResponse" do
    optional :show_challenge, :bool, 1
    optional :challenge_url, :string, 2
  end
end

module POGOProtos
  module Networking
    module Responses
      CheckChallengeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.CheckChallengeResponse").msgclass
    end
  end
end
