# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/encounter_response.proto

require 'google/protobuf'

require 'pogoprotos/data/capture/capture_probability_pb'
require 'pogoprotos/inventory/item/item_id_pb'
require 'pogoprotos/map/pokemon/wild_pokemon_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.EncounterResponse" do
    optional :wild_pokemon, :message, 1, "POGOProtos.Map.Pokemon.WildPokemon"
    optional :background, :enum, 2, "POGOProtos.Networking.Responses.EncounterResponse.Background"
    optional :status, :enum, 3, "POGOProtos.Networking.Responses.EncounterResponse.Status"
    optional :capture_probability, :message, 4, "POGOProtos.Data.Capture.CaptureProbability"
    optional :active_item, :enum, 5, "POGOProtos.Inventory.Item.ItemId"
  end
  add_enum "POGOProtos.Networking.Responses.EncounterResponse.Background" do
    value :PARK, 0
    value :DESERT, 1
  end
  add_enum "POGOProtos.Networking.Responses.EncounterResponse.Status" do
    value :ENCOUNTER_ERROR, 0
    value :ENCOUNTER_SUCCESS, 1
    value :ENCOUNTER_NOT_FOUND, 2
    value :ENCOUNTER_CLOSED, 3
    value :ENCOUNTER_POKEMON_FLED, 4
    value :ENCOUNTER_NOT_IN_RANGE, 5
    value :ENCOUNTER_ALREADY_HAPPENED, 6
    value :POKEMON_INVENTORY_FULL, 7
    value :ENCOUNTER_BLOCKED_BY_ANTICHEAT, 8
  end
end

module POGOProtos
  module Networking
    module Responses
      EncounterResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.EncounterResponse").msgclass
      EncounterResponse::Background = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.EncounterResponse.Background").enummodule
      EncounterResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.EncounterResponse.Status").enummodule
    end
  end
end
