# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/evolve_pokemon_response.proto

require 'google/protobuf'

require 'pogoprotos/data/pokemon_data_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.EvolvePokemonResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.EvolvePokemonResponse.Result"
    optional :evolved_pokemon_data, :message, 2, "POGOProtos.Data.PokemonData"
    optional :experience_awarded, :int32, 3
    optional :candy_awarded, :int32, 4
  end
  add_enum "POGOProtos.Networking.Responses.EvolvePokemonResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :FAILED_POKEMON_MISSING, 2
    value :FAILED_INSUFFICIENT_RESOURCES, 3
    value :FAILED_POKEMON_CANNOT_EVOLVE, 4
    value :FAILED_POKEMON_IS_DEPLOYED, 5
    value :FAILED_INVALID_ITEM_REQUIREMENT, 6
  end
end

module POGOProtos
  module Networking
    module Responses
      EvolvePokemonResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.EvolvePokemonResponse").msgclass
      EvolvePokemonResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.EvolvePokemonResponse.Result").enummodule
    end
  end
end
