# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/get_player_response.proto

require 'google/protobuf'

require 'pogoprotos/data/player_data_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetPlayerResponse" do
    optional :success, :bool, 1
    optional :player_data, :message, 2, "POGOProtos.Data.PlayerData"
    optional :banned, :bool, 3
    optional :warn, :bool, 4
  end
end

module POGOProtos
  module Networking
    module Responses
      GetPlayerResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetPlayerResponse").msgclass
    end
  end
end
