# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/get_asset_digest_response.proto

require 'google/protobuf'

require 'pogoprotos/data/asset_digest_entry_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetAssetDigestResponse" do
    repeated :digest, :message, 1, "POGOProtos.Data.AssetDigestEntry"
    optional :timestamp_ms, :uint64, 2
    optional :result, :enum, 3, "POGOProtos.Networking.Responses.GetAssetDigestResponse.Result"
    optional :page_offset, :int32, 4
  end
  add_enum "POGOProtos.Networking.Responses.GetAssetDigestResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :PAGE, 2
    value :RETRY, 3
  end
end

module POGOProtos
  module Networking
    module Responses
      GetAssetDigestResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetAssetDigestResponse").msgclass
      GetAssetDigestResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetAssetDigestResponse.Result").enummodule
    end
  end
end
