# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/get_gym_details_response.proto

require 'google/protobuf'

require 'pogoprotos/data/gym/gym_state_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetGymDetailsResponse" do
    optional :gym_state, :message, 1, "POGOProtos.Data.Gym.GymState"
    optional :name, :string, 2
    repeated :urls, :string, 3
    optional :result, :enum, 4, "POGOProtos.Networking.Responses.GetGymDetailsResponse.Result"
    optional :description, :string, 5
    repeated :secondary_url, :string, 6
  end
  add_enum "POGOProtos.Networking.Responses.GetGymDetailsResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :ERROR_NOT_IN_RANGE, 2
  end
end

module POGOProtos
  module Networking
    module Responses
      GetGymDetailsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetGymDetailsResponse").msgclass
      GetGymDetailsResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetGymDetailsResponse.Result").enummodule
    end
  end
end
