# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/get_hatched_eggs_response.proto

require 'google/protobuf'

require 'pogoprotos/data/pokemon_data_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetHatchedEggsResponse" do
    optional :success, :bool, 1
    repeated :pokemon_id, :fixed64, 2
    repeated :experience_awarded, :int32, 3
    repeated :candy_awarded, :int32, 4
    repeated :stardust_awarded, :int32, 5
    repeated :egg_km_walked, :float, 6
    repeated :hatched_pokemon, :message, 7, "POGOProtos.Data.PokemonData"
  end
end

module POGOProtos
  module Networking
    module Responses
      GetHatchedEggsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetHatchedEggsResponse").msgclass
    end
  end
end
