# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/get_map_objects_response.proto

require 'google/protobuf'

require 'pogoprotos/map/map_cell_pb'
require 'pogoprotos/map/map_objects_status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetMapObjectsResponse" do
    repeated :map_cells, :message, 1, "POGOProtos.Map.MapCell"
    optional :status, :enum, 2, "POGOProtos.Map.MapObjectsStatus"
    optional :time_of_day, :enum, 3, "POGOProtos.Networking.Responses.GetMapObjectsResponse.TimeOfDay"
  end
  add_enum "POGOProtos.Networking.Responses.GetMapObjectsResponse.TimeOfDay" do
    value :NONE, 0
    value :DAY, 1
    value :NIGHT, 2
  end
end

module POGOProtos
  module Networking
    module Responses
      GetMapObjectsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetMapObjectsResponse").msgclass
      GetMapObjectsResponse::TimeOfDay = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetMapObjectsResponse.TimeOfDay").enummodule
    end
  end
end
