# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/get_buddy_walked_response.proto

require 'google/protobuf'

require 'pogoprotos/enums/pokemon_family_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetBuddyWalkedResponse" do
    optional :success, :bool, 1
    optional :family_candy_id, :enum, 2, "POGOProtos.Enums.PokemonFamilyId"
    optional :candy_earned_count, :int32, 3
  end
end

module POGOProtos
  module Networking
    module Responses
      GetBuddyWalkedResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetBuddyWalkedResponse").msgclass
    end
  end
end
