# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/get_player_profile_response.proto

require 'google/protobuf'

require 'pogoprotos/data/player_badge_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetPlayerProfileResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.GetPlayerProfileResponse.Result"
    optional :start_time, :int64, 2
    repeated :badges, :message, 3, "POGOProtos.Data.PlayerBadge"
  end
  add_enum "POGOProtos.Networking.Responses.GetPlayerProfileResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
  end
end

module POGOProtos
  module Networking
    module Responses
      GetPlayerProfileResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetPlayerProfileResponse").msgclass
      GetPlayerProfileResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetPlayerProfileResponse.Result").enummodule
    end
  end
end
