# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/list_avatar_customizations_response.proto

require 'google/protobuf'

require 'pogoprotos/data/avatar/avatar_customization_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.ListAvatarCustomizationsResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.ListAvatarCustomizationsResponse.Result"
    optional :avatar_customizations, :message, 2, "POGOProtos.Data.Avatar.AvatarCustomization"
  end
  add_enum "POGOProtos.Networking.Responses.ListAvatarCustomizationsResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :FAILURE, 2
  end
end

module POGOProtos
  module Networking
    module Responses
      ListAvatarCustomizationsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.ListAvatarCustomizationsResponse").msgclass
      ListAvatarCustomizationsResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.ListAvatarCustomizationsResponse.Result").enummodule
    end
  end
end
