# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/mark_tutorial_complete_response.proto

require 'google/protobuf'

require 'pogoprotos/data/player_data_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.MarkTutorialCompleteResponse" do
    optional :success, :bool, 1
    optional :player_data, :message, 2, "POGOProtos.Data.PlayerData"
  end
end

module POGOProtos
  module Networking
    module Responses
      MarkTutorialCompleteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.MarkTutorialCompleteResponse").msgclass
    end
  end
end
