# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/push_notification_registry_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.PushNotificationRegistryResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.PushNotificationRegistryResponse.Result"
  end
  add_enum "POGOProtos.Networking.Responses.PushNotificationRegistryResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :NO_CHANGE, 2
  end
end

module POGOProtos
  module Networking
    module Responses
      PushNotificationRegistryResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.PushNotificationRegistryResponse").msgclass
      PushNotificationRegistryResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.PushNotificationRegistryResponse.Result").enummodule
    end
  end
end
