# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/register_background_device_response.proto

require 'google/protobuf'

require 'pogoprotos/data/background_token_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.RegisterBackgroundDeviceResponse" do
    optional :status, :enum, 1, "POGOProtos.Networking.Responses.RegisterBackgroundDeviceResponse.Status"
    optional :token, :message, 2, "POGOProtos.Data.BackgroundToken"
  end
  add_enum "POGOProtos.Networking.Responses.RegisterBackgroundDeviceResponse.Status" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :ERROR, 2
  end
end

module POGOProtos
  module Networking
    module Responses
      RegisterBackgroundDeviceResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.RegisterBackgroundDeviceResponse").msgclass
      RegisterBackgroundDeviceResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.RegisterBackgroundDeviceResponse.Status").enummodule
    end
  end
end
