# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/set_avatar_response.proto

require 'google/protobuf'

require 'pogoprotos/data/player_data_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.SetAvatarResponse" do
    optional :status, :enum, 1, "POGOProtos.Networking.Responses.SetAvatarResponse.Status"
    optional :player_data, :message, 2, "POGOProtos.Data.PlayerData"
  end
  add_enum "POGOProtos.Networking.Responses.SetAvatarResponse.Status" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :AVATAR_ALREADY_SET, 2
    value :FAILURE, 3
    value :SLOT_NOT_ALLOWED, 4
    value :ITEM_NOT_OWNED, 5
    value :INVALID_AVATAR_TYPE, 6
  end
end

module POGOProtos
  module Networking
    module Responses
      SetAvatarResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetAvatarResponse").msgclass
      SetAvatarResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetAvatarResponse.Status").enummodule
    end
  end
end
