# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/set_avatar_item_as_viewed_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.SetAvatarItemAsViewedResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.SetAvatarItemAsViewedResponse.Result"
  end
  add_enum "POGOProtos.Networking.Responses.SetAvatarItemAsViewedResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :FAILURE, 2
  end
end

module POGOProtos
  module Networking
    module Responses
      SetAvatarItemAsViewedResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetAvatarItemAsViewedResponse").msgclass
      SetAvatarItemAsViewedResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetAvatarItemAsViewedResponse.Result").enummodule
    end
  end
end
