# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/set_contact_settings_response.proto

require 'google/protobuf'

require 'pogoprotos/data/player_data_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.SetContactSettingsResponse" do
    optional :status, :enum, 1, "POGOProtos.Networking.Responses.SetContactSettingsResponse.Status"
    optional :player_data, :message, 2, "POGOProtos.Data.PlayerData"
  end
  add_enum "POGOProtos.Networking.Responses.SetContactSettingsResponse.Status" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :FAILURE, 2
  end
end

module POGOProtos
  module Networking
    module Responses
      SetContactSettingsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetContactSettingsResponse").msgclass
      SetContactSettingsResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetContactSettingsResponse.Status").enummodule
    end
  end
end
