# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/set_buddy_pokemon_response.proto

require 'google/protobuf'

require 'pogoprotos/data/buddy_pokemon_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.SetBuddyPokemonResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.SetBuddyPokemonResponse.Result"
    optional :updated_buddy, :message, 2, "POGOProtos.Data.BuddyPokemon"
  end
  add_enum "POGOProtos.Networking.Responses.SetBuddyPokemonResponse.Result" do
    value :UNEST, 0
    value :SUCCESS, 1
    value :ERROR_POKEMON_DEPLOYED, 2
    value :ERROR_POKEMON_NOT_OWNED, 3
    value :ERROR_POKEMON_IS_EGG, 4
  end
end

module POGOProtos
  module Networking
    module Responses
      SetBuddyPokemonResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetBuddyPokemonResponse").msgclass
      SetBuddyPokemonResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetBuddyPokemonResponse.Result").enummodule
    end
  end
end
