# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/sfida_action_log_response.proto

require 'google/protobuf'

require 'pogoprotos/data/logs/action_log_entry_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.SfidaActionLogResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.SfidaActionLogResponse.Result"
    repeated :log_entries, :message, 2, "POGOProtos.Data.Logs.ActionLogEntry"
  end
  add_enum "POGOProtos.Networking.Responses.SfidaActionLogResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
  end
end

module POGOProtos
  module Networking
    module Responses
      SfidaActionLogResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SfidaActionLogResponse").msgclass
      SfidaActionLogResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SfidaActionLogResponse.Result").enummodule
    end
  end
end
