# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/upgrade_pokemon_response.proto

require 'google/protobuf'

require 'pogoprotos/data/pokemon_data_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.UpgradePokemonResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.UpgradePokemonResponse.Result"
    optional :upgraded_pokemon, :message, 2, "POGOProtos.Data.PokemonData"
  end
  add_enum "POGOProtos.Networking.Responses.UpgradePokemonResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :ERROR_POKEMON_NOT_FOUND, 2
    value :ERROR_INSUFFICIENT_RESOURCES, 3
    value :ERROR_UPGRADE_NOT_AVAILABLE, 4
    value :ERROR_POKEMON_IS_DEPLOYED, 5
  end
end

module POGOProtos
  module Networking
    module Responses
      UpgradePokemonResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.UpgradePokemonResponse").msgclass
      UpgradePokemonResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.UpgradePokemonResponse.Result").enummodule
    end
  end
end
