# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/use_item_capture_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.UseItemCaptureResponse" do
    optional :success, :bool, 1
    optional :item_capture_mult, :double, 2
    optional :item_flee_mult, :double, 3
    optional :stop_movement, :bool, 4
    optional :stop_attack, :bool, 5
    optional :target_max, :bool, 6
    optional :target_slow, :bool, 7
  end
end

module POGOProtos
  module Networking
    module Responses
      UseItemCaptureResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.UseItemCaptureResponse").msgclass
    end
  end
end
