# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/use_item_encounter_response.proto

require 'google/protobuf'

require 'pogoprotos/data/capture/capture_probability_pb'
require 'pogoprotos/inventory/item/item_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.UseItemEncounterResponse" do
    optional :status, :enum, 1, "POGOProtos.Networking.Responses.UseItemEncounterResponse.Status"
    optional :capture_probability, :message, 2, "POGOProtos.Data.Capture.CaptureProbability"
    optional :active_item, :enum, 3, "POGOProtos.Inventory.Item.ItemId"
  end
  add_enum "POGOProtos.Networking.Responses.UseItemEncounterResponse.Status" do
    value :SUCCESS, 0
    value :ALREADY_COMPLETED, 1
    value :ACTIVE_ITEM_EXISTS, 2
    value :NO_ITEM_IN_INVENTORY, 3
    value :INVALID_ITEM_CATEGORY, 4
  end
end

module POGOProtos
  module Networking
    module Responses
      UseItemEncounterResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.UseItemEncounterResponse").msgclass
      UseItemEncounterResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.UseItemEncounterResponse.Status").enummodule
    end
  end
end
