# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/use_item_xp_boost_response.proto

require 'google/protobuf'

require 'pogoprotos/inventory/applied_items_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.UseItemXpBoostResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.UseItemXpBoostResponse.Result"
    optional :applied_items, :message, 2, "POGOProtos.Inventory.AppliedItems"
  end
  add_enum "POGOProtos.Networking.Responses.UseItemXpBoostResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :ERROR_INVALID_ITEM_TYPE, 2
    value :ERROR_XP_BOOST_ALREADY_ACTIVE, 3
    value :ERROR_NO_ITEMS_REMAINING, 4
    value :ERROR_LOCATION_UNSET, 5
  end
end

module POGOProtos
  module Networking
    module Responses
      UseItemXpBoostResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.UseItemXpBoostResponse").msgclass
      UseItemXpBoostResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.UseItemXpBoostResponse.Result").enummodule
    end
  end
end
