# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/verify_challenge_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.VerifyChallengeResponse" do
    optional :success, :bool, 1
  end
end

module POGOProtos
  module Networking
    module Responses
      VerifyChallengeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.VerifyChallengeResponse").msgclass
    end
  end
end
