# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/redeem/poke_candy.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Redeem.PokeCandy" do
    optional :pokemon_id, :fixed64, 1
    optional :candy_count, :int32, 2
  end
end

module POGOProtos
  module Data
    module Redeem
      PokeCandy = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Redeem.PokeCandy").msgclass
    end
  end
end
