# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/redeem/redeemed_avatar_item.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Redeem.RedeemedAvatarItem" do
    optional :avatar_template_id, :string, 1
    optional :item_count, :int32, 2
  end
end

module POGOProtos
  module Data
    module Redeem
      RedeemedAvatarItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Redeem.RedeemedAvatarItem").msgclass
    end
  end
end
