# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/redeem/redeemed_item.proto

require 'google/protobuf'

require 'pogoprotos/inventory/item/item_id_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Redeem.RedeemedItem" do
    optional :item, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :item_count, :int32, 2
  end
end

module POGOProtos
  module Data
    module Redeem
      RedeemedItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Redeem.RedeemedItem").msgclass
    end
  end
end
