# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/gym/gym_membership.proto

require 'google/protobuf'

require 'pogoprotos/data/pokemon_data_pb'
require 'pogoprotos/data/player/player_public_profile_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Gym.GymMembership" do
    optional :pokemon_data, :message, 1, "POGOProtos.Data.PokemonData"
    optional :trainer_public_profile, :message, 2, "POGOProtos.Data.Player.PlayerPublicProfile"
    optional :training_pokemon, :message, 3, "POGOProtos.Data.PokemonData"
  end
end

module POGOProtos
  module Data
    module Gym
      GymMembership = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Gym.GymMembership").msgclass
    end
  end
end
