# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/gym/gym_state.proto

require 'google/protobuf'

require 'pogoprotos/map/fort/fort_data_pb'
require 'pogoprotos/data/gym/gym_membership_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Gym.GymState" do
    optional :fort_data, :message, 1, "POGOProtos.Map.Fort.FortData"
    repeated :memberships, :message, 2, "POGOProtos.Data.Gym.GymMembership"
    optional :deploy_lockout, :bool, 3
  end
end

module POGOProtos
  module Data
    module Gym
      GymState = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Gym.GymState").msgclass
    end
  end
end
