# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/player/player_camera.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Player.PlayerCamera" do
    optional :is_default_camera, :bool, 1
  end
end

module POGOProtos
  module Data
    module Player
      PlayerCamera = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Player.PlayerCamera").msgclass
    end
  end
end
