# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/player/player_avatar_type.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Data.Player.PlayerAvatarType" do
    value :PLAYER_AVATAR_MALE, 0
    value :PLAYER_AVATAR_FEMALE, 1
  end
end

module POGOProtos
  module Data
    module Player
      PlayerAvatarType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Player.PlayerAvatarType").enummodule
    end
  end
end
