# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/player/player_avatar.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Player.PlayerAvatar" do
    optional :skin, :int32, 2
    optional :hair, :int32, 3
    optional :shirt, :int32, 4
    optional :pants, :int32, 5
    optional :hat, :int32, 6
    optional :shoes, :int32, 7
    optional :avatar, :int32, 8
    optional :eyes, :int32, 9
    optional :backpack, :int32, 10
    optional :avatar_hair, :string, 11
    optional :avatar_shirt, :string, 12
    optional :avatar_pants, :string, 13
    optional :avatar_hat, :string, 14
    optional :avatar_shoes, :string, 15
    optional :avatar_eyes, :string, 16
    optional :avatar_backpack, :string, 17
    optional :avatar_gloves, :string, 18
    optional :avatar_socks, :string, 19
    optional :avatar_belt, :string, 20
    optional :avatar_glasses, :string, 21
    optional :avatar_necklace, :string, 22
  end
end

module POGOProtos
  module Data
    module Player
      PlayerAvatar = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Player.PlayerAvatar").msgclass
    end
  end
end
